### ISSUE TITLE
LVT doesn't work

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk-old#270]
No LVT burden, e.g. https://uk.policyengine.org/population-results?LVT=1

**Comment by nikhilwoodruff** [comment]
Found the source (uprating not carrying forward land values: 2019 land values exist, but not 2020)

**Comment by nikhilwoodruff** [comment]
Found it - the issue is that by default, every input variable is uprated (or at least carried over) to consecutive years. However, this imputation line was changed (by me, not realising the effect) recently, to happen before applying the reforms, rather than after. This meant that since the land value variable is added by a reform, it missed the original uprating.
